default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("PUMA_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

production:
  <<: *default
  database: prod